name: ideal_calcule
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_launcher_icons: "^0.13.1"
  google_fonts: ^6.1.0
  intl: ^0.19.0
  sqflite: ^2.3.0
  sqflite_common_ffi: ^2.3.0
  path: ^1.8.3
  path_provider: ^2.1.1
  image_picker: ^1.0.4
  file_selector: ^1.0.1
  fl_chart: ^0.65.0
  shared_preferences: ^2.2.2
  toggle_switch: ^2.1.0
  share_plus: ^12.0.1
  pdf: ^3.11.3
  printing: ^5.14.2
  supabase_flutter: ^2.10.3
  data_table_2: ^2.7.2
  provider: ^6.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/ideal_logo.jpg

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/ideal_logo.jpg"
  windows:
    generate: true
    image_path: "assets/images/ideal_logo.jpg"
    icon_size: 48